/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class FrmPrestamo extends javax.swing.JDialog {

    /**
     * Creates new form FrmPrestamo
     */
    public FrmPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
 public static FrmPrestamo open() {
        FrmPrestamo frm = new FrmPrestamo(null, false);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        return frm;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        input_nombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        input_nombre1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        panel_lector = new javax.swing.JPanel();
        datospanel = new javax.swing.JPanel();
        input = new javax.swing.JPanel();
        input_nombre2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIInfoLector = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel2.setPreferredSize(new java.awt.Dimension(550, 60));
        jPanel2.setLayout(new java.awt.BorderLayout(80, 0));

        input_nombre.setPreferredSize(new java.awt.Dimension(250, 60));
        input_nombre.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha:");
        input_nombre.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        input_nombre.add(jDateChooser1, java.awt.BorderLayout.CENTER);

        jPanel2.add(input_nombre, java.awt.BorderLayout.LINE_START);

        input_nombre1.setPreferredSize(new java.awt.Dimension(250, 60));
        input_nombre1.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Número de Prestamo:");
        input_nombre1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        txtName1.setPreferredSize(new java.awt.Dimension(80, 30));
        input_nombre1.add(txtName1, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(input_nombre1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2);

        datospanel.setPreferredSize(new java.awt.Dimension(355, 150));

        input.setPreferredSize(new java.awt.Dimension(360, 70));

        input_nombre2.setPreferredSize(new java.awt.Dimension(250, 60));
        input_nombre2.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Dni Lector:");
        input_nombre2.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        txtName2.setPreferredSize(new java.awt.Dimension(80, 30));
        input_nombre2.add(txtName2, java.awt.BorderLayout.PAGE_END);

        input.add(input_nombre2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchmagnifierinterfacesymbol1_79893.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(10);
        jButton1.setMargin(new java.awt.Insets(10, 20, 25, 14));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        input.add(jButton1);

        jButton2.setText("jButton2");

        javax.swing.GroupLayout datospanelLayout = new javax.swing.GroupLayout(datospanel);
        datospanel.setLayout(datospanelLayout);
        datospanelLayout.setHorizontalGroup(
            datospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(datospanelLayout.createSequentialGroup()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        datospanelLayout.setVerticalGroup(
            datospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datospanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        panel_lector.add(datospanel);

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        txtIInfoLector.setColumns(20);
        txtIInfoLector.setRows(5);
        jScrollPane1.setViewportView(txtIInfoLector);

        jPanel5.add(jScrollPane1);

        panel_lector.add(jPanel5);

        jPanel1.add(panel_lector);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("libros:");
        jPanel4.add(jLabel5);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(453, 250));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel4.add(jScrollPane3);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrestamo dialog = new FrmPrestamo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datospanel;
    private javax.swing.JPanel input;
    private javax.swing.JPanel input_nombre;
    private javax.swing.JPanel input_nombre1;
    private javax.swing.JPanel input_nombre2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panel_lector;
    private javax.swing.JTextArea txtIInfoLector;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    // End of variables declaration//GEN-END:variables
}
